### PR TITLE
Add content type param

### PR DESCRIPTION
**Pull request by marsmans13**
Add optional parameter for content_type to support v3 of the API

### CODE REVIEW

**Comment by pepecommops** [comment]
Argo CI comment: Looks good to me! and your package is here <a href=https://nexus.pepstaging.com/#browse/browse:pypi-dev:amazon-advertising-api-python/0.0.0-devca7973c>0.0.0-devca7973c</a>

**Comment by pepecommops** [comment]
Argo CI comment: Looks good to me! and your package is here <a href=https://nexus.pepstaging.com/#browse/browse:pypi-dev:amazon-advertising-api-python/0.0.0-dev9616dab>0.0.0-dev9616dab</a>

**Comment by pepecommops** [comment]
Argo CI comment: Looks good to me! and your package is here <a href=https://nexus.pepstaging.com/#browse/browse:pypi-dev:amazon-advertising-api-python/0.0.0-dev53fb78d>0.0.0-dev53fb78d</a>

**Review by ilov3 — APPROVED** [review]
lgtm

**Pull request merged**
