### PR TITLE
fix application version reference for bumpversion and runtime

### PR DESCRIPTION
**Pull request by dkoryukova**
Set up module version variable in a way that works both for bumpversion lib (Used on CI) and available on runtime.

### CODE REVIEW

**Comment by pepecommops** [comment]
Argo CI comment: Looks good to me! and your package is here <a href=https://nexus.pepstaging.com/#browse/browse:pypi-dev:amazon-advertising-api-python/0.0.0-devf1d9b72>0.0.0-devf1d9b72</a>

**Comment by pepecommops** [comment]
Argo CI comment: Looks good to me! and your package is here <a href=https://nexus.pepstaging.com/#browse/browse:pypi-dev:amazon-advertising-api-python/0.0.0-devfa93595>0.0.0-devfa93595</a>

**Comment by pepecommops** [comment]
Argo CI comment: Looks good to me! and your package is here <a href=https://nexus.pepstaging.com/#browse/browse:pypi-dev:amazon-advertising-api-python/0.0.0-devf38b913>0.0.0-devf38b913</a>

**Comment by pepecommops** [comment]
Argo CI comment: Looks good to me! and your package is here <a href=https://nexus.pepstaging.com/#browse/browse:pypi-dev:amazon-advertising-api-python/0.0.0-devf38b913>0.0.0-devf38b913</a>

**Review by techkuz — APPROVED** [review]
lgtm

**Pull request merged**
